#!/usr/bin/expect -f
set passwd [lindex $argv 0]
spawn ssh-keygen
expect {
  "*yes/no*" {
     send "yes\r"
     exp_continue
  } "*password*" {
    send "$passwd\r"
    exp_continue
  } "*file" {
    send "\n"
    exp_continue
  } "*passphrase*" {
    send "\n"
    exp_continue
  } "*y/n*" {
    send "y\r"
    exp_continue
  } "*again*" {
    send "\n"
    exp_continue
  } eof {
    exit
  }
   
}
