/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef heartbeat_CONSTANTS_H
#define heartbeat_CONSTANTS_H

#include "heartbeat_types.h"



class heartbeatConstants {
 public:
  heartbeatConstants();

};

extern const heartbeatConstants g_heartbeat_constants;



#endif
